CREATE DATABASE temp1;
DROP DATABASE temp1;

CREATE DATABASE college;
USE college;

CREATE TABLE student(
	ID INT primary key,
    NAME VARCHAR(50),
    AGE INT NOT NULL,
    ENROLLMENT BIGINT NOT NULL
);

INSERT INTO student (ID, NAME, AGE, ENROLLMENT) VALUES (1,"Souvik",22,22021002011021);
INSERT INTO student VALUES(2,"Vidhi",21,12020002011013);

SELECT * FROM student;
SELECT NAME FROM student;


CREATE DATABASE temp1;
CREATE DATABASE IF NOT EXISTS temp1;

DROP DATABASE temp1;

DROP DATABASE temp2;
DROP DATABASE IF EXISTS temp2;

SHOW DATABASES;
SHOW TABLES;
