CREATE DATABASE BCCI;
USE BCCI;

CREATE TABLE CAPTAINS(
	NAME VARCHAR(50) NOT NULL,
	YEAR BIGINT PRIMARY KEY,
    JERSEY_NO INT
);

INSERT INTO CAPTAINS VALUES("MS DHONI",2007,7);
INSERT INTO CAPTAINS VALUES("VIRAT KOHLI",2017,18);

# use of SELECT command : 

SELECT * FROM CAPTAINS;  #selects whole table
SELECT NAME FROM CAPTAINS;  #selects only mentioned datas
SELECT NAME, JERSEY_NO FROM CAPTAINS;



# use of DISTINCT command : 

CREATE DATABASE EMPLOYEES_DATA;
USE EMPLOYEES_DATA;

CREATE TABLE EMP_INFO(
	ID INT PRIMARY KEY,
	NAME VARCHAR(50) NOT NULL,
    CITY VARCHAR(50) NOT NULL,
    SALARY BIGINT NOT NULL
);

INSERT INTO EMP_INFO VALUES(1,"SOUVIK","KOLKATA",30000);
INSERT INTO EMP_INFO VALUES(2,"VIDHI","KOLKATA",50000);
INSERT INTO EMP_INFO VALUES(3,"ELON","NEW YORK",45000);
INSERT INTO EMP_INFO VALUES(4,"NOBITA","TOKYO",60000);
INSERT INTO EMP_INFO VALUES(5,"RODGER","LONDON",70000);
INSERT INTO EMP_INFO VALUES(6,"SUNIO","TOKYO",75000);

SELECT DISTINCT CITY FROM CITIES;  #only stores the distinct values


# use of WHERE clause :

SELECT * FROM EMP_INFO WHERE SALARY>=50000;
SELECT NAME FROM EMP_INFO WHERE SALARY>=50000 AND CITY="KOLKATA";

# use of Operators in WHERE clause :
# Arithmatic Operators : +, -, *, /, %
# Comparison Opeartors : =, !=, >, <, >=, <=
# Logical Operators : AND, OR, NOT, IN, BETWEEN, ALL, LIKE, ANY
# Bitwise Operator : & (Bitwise AND), | (Bitwise OR)

# example of Arithmatic Operators : 
SELECT * FROM EMP_INFO WHERE SALARY+10000>=50000;

# example of Logical Operator : AND
SELECT * FROM EMP_INFO WHERE SALARY>=50000 AND CITY="TOKYO";  #Both the conditions must be true

# Logical Operator : BETWEEN
SELECT * FROM EMP_INFO WHERE SALARY BETWEEN 30000 AND 60000;

# Logical Operator : IN
SELECT * FROM EMP_INFO WHERE CITY IN ("KOLKATA","NEW YORK");

# Logical Operator : NOT
SELECT * FROM EMP_INFO WHERE CITY NOT IN ("KOLKATA","NEW YORK");




# LIMIT clause : sets an upper limit on number of rows to be retured
SELECT * FROM EMP_INFO LIMIT 2;
SELECT * FROM EMP_INFO WHERE SALARY>25000 LIMIT 3;




# ORDER BY clause : to sort in ascending (ASC) or descending (DESC) order
SELECT * FROM EMP_INFO ORDER BY CITY ASC;
SELECT * FROM EMP_INFO ORDER BY ID DESC;

# if we have to get 3 most paid employees :
SELECT * FROM EMP_INFO ORDER BY SALARY DESC LIMIT 3;