# Aggregate functions perform a calculation on a set of values and return a single value -->
# COUNT();
# MAX();
# MIN();
# SUM();
# AVG();

CREATE DATABASE STUDENTS_PERFORMANCE;
USE STUDENTS_PERFORMANCE;

CREATE TABLE EXAM(
	ROLL_NO INT PRIMARY KEY,
	NAME VARCHAR(50),
    MARKS INT NOT NULL,
    CITY VARCHAR(50)
);

INSERT INTO EXAM VALUES(101,"SOUVIK",77,"ASANSOL");
INSERT INTO EXAM VALUES(102,"VIDHI",98,"KOLKATA");
INSERT INTO EXAM VALUES(103,"RAHUL",79,"ASANSOL");
INSERT INTO EXAM VALUES(104,"AMAN",51,"MUMBAI");
INSERT INTO EXAM VALUES(105,"ABHI",65,"DELHI");
INSERT INTO EXAM VALUES(106,"SID",89,"HYDERABAD");
INSERT INTO EXAM VALUES(107,"HARRY",79,"MUMBAI");

# using functions :
SELECT MAX(MARKS) FROM EXAM;
SELECT AVG(MARKS) FROM EXAM;
SELECT COUNT(NAME) FROM EXAM;
SELECT SUM(MARKS) FROM EXAM;
