# GROUP BY CLAUSE : Groups rows that have the same vlaues into summary rows.
# generally we use group by with some aggregation function.

CREATE DATABASE STUDENTS_PERFORMANCE_01;
USE STUDENTS_PERFORMANCE_01;

CREATE TABLE EXAM_01(
	ROLL_NO INT PRIMARY KEY,
	NAME VARCHAR(50),
    MARKS INT NOT NULL,
    CITY VARCHAR(50)
);

INSERT INTO EXAM_01 VALUES(101,"SOUVIK",77,"ASANSOL");
INSERT INTO EXAM_01 VALUES(102,"VIDHI",98,"KOLKATA");
INSERT INTO EXAM_01 VALUES(103,"RAHUL",79,"ASANSOL");
INSERT INTO EXAM_01 VALUES(104,"AMAN",51,"MUMBAI");
INSERT INTO EXAM_01 VALUES(105,"ABHI",65,"DELHI");
INSERT INTO EXAM_01 VALUES(106,"SID",89,"HYDERABAD");
INSERT INTO EXAM_01 VALUES(107,"HARRY",79,"MUMBAI");

SELECT CITY FROM EXAM_01 GROUP BY CITY;
SELECT NAME FROM EXAM_01 GROUP BY NAME;
SELECT CITY, COUNT(NAME) FROM EXAM_01 GROUP BY CITY;
SELECT CITY, SUM(MARKS) FROM EXAM_01 GROUP BY CITY;
SELECT CITY, AVG(MARKS) FROM EXAM_01 GROUP BY CITY;