# ALTER Command : to change the Schema (Columns, Datatype, Constraints)

CREATE DATABASE STUDENTS_PERFORMANCE_04;
USE STUDENTS_PERFORMANCE_04;

CREATE TABLE EXAM_04(
	ROLL_NO INT PRIMARY KEY,
	NAME VARCHAR(50),
    MARKS INT NOT NULL,
    CITY VARCHAR(50)
);

INSERT INTO EXAM_04 VALUES(101,"SOUVIK",77,"ASANSOL");
INSERT INTO EXAM_04 VALUES(102,"VIDHI",98,"KOLKATA");
INSERT INTO EXAM_04 VALUES(103,"RAHUL",79,"ASANSOL");
INSERT INTO EXAM_04 VALUES(104,"AMAN",51,"MUMBAI");
INSERT INTO EXAM_04 VALUES(105,"ABHI",65,"DELHI");
INSERT INTO EXAM_04 VALUES(106,"SID",89,"HYDERABAD");
INSERT INTO EXAM_04 VALUES(107,"HARRY",79,"MUMBAI");

# add & delete Column :
ALTER TABLE EXAM_04 ADD COLUMN AGE INT;  # to add column
SELECT * FROM EXAM_04;

ALTER TABLE EXAM_04 DROP COLUMN AGE;  # to delete column
SELECT * FROM EXAM_04;

# Rename Table name :
ALTER TABLE EXAM_04 RENAME TO EXAM_DETAILS; # to rename the table
SELECT * FROM EXAM_DETAILS;
ALTER TABLE EXAM_DETAILS RENAME TO EXAM_04;

# Change column Name :  ALTER TABLE table_name CHANGE COLUMN old_name  new_name  new_constraint
ALTER TABLE EXAM_04
CHANGE COLUMN ROLL_NO STUDENT_ID INT;
SELECT * FROM EXAM_04;

# Modify Column's Datatype & Constraint : ALTER TABLE tbale_name MODIFY column_name  new_Datatype  new_Contraint
ALTER TABLE EXAM_04
MODIFY NAME VARCHAR(20) NOT NULL;
SELECT * FROM EXAM_04;